web/router.ex
defmodule Auction.Router do
  use Auction.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Auction do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController do
      resources "/auctions", AuctionController
      resources "/bids", BidController, only: [:index, :show]
    end
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/auctions", AuctionController do
      resources "/bids", BidController, only: [:index, :new, :create, :show]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Auction do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to the auction page" %></h2>
  <p class="lead">A simple demo app that<br />allows to create auctions and bid on them.</p>
</div>

<div class="row marketing">

  <%= if user = current_user(@conn) do %>
    <div class="col-lg-6">
      <h4>Auctions</h4>
      <ul>
        <li>
          <%= link "My auctions", to: user_auction_path(@conn, :index, user.id) %>
        </li>
        <li>
          <%= link "All auctions", to: auction_path(@conn, :index) %>
        </li>
      </ul>
    </div>

    <div class="col-lg-6">
      <h4>Bids</h4>
      <ul>
        <li>
          <%= link "My bids", to: user_bid_path(@conn, :index, user.id) %>
        </li>
      </ul>
    </div>
  <% else %>
    <%= link "Register", to: user_path(@conn, :new) %>
  <% end %>

</div>